# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
     branches: [ master ]
  pull_request:
     branches: [ master ]

jobs:
  build:
     runs-on: ubuntu-latest
     services:
        postgres:
          image: postgres:11.6-alpine
          env:
             POSTGRES_PASSWORD: postgres
             POSTGRES_DB: test
             POSTGRES_USER: postgres
          ports:
             - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
     steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.15
          uses: actions/setup-java@v1
          with:
             java-version: 1.15
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build
          run: DB_NAME=test DB_PASSWORD=postgres DB_USER=postgres JPA_DDL=validate VALIDATE_DB=true  ./gradlew build --scan
        - name: Style check and tests
          run: DB_NAME=test DB_PASSWORD=postgres DB_USER=postgres JPA_DDL=validate VALIDATE_DB=true ./gradlew check --scan
